language: python
python:
  - "3.6"
  - "3.8"
install:
  - "pip install -e ."
  - "pip install -e .[test]"
  - "pip install coveralls>=1.1"
script: "py.test --cov tpkutils --cov-report term-missing"
after_success:
  - coveralls || echo "!! intermittent coveralls failure"
